spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservou_db?serverTimezone=America/Sao_Paulo
    username: postgres
    password: aluno
    #    url: jdbc:postgresql://db:5432/reservou_db?serverTimezone=America/Sao_Paulo
    #    username: admin
    #    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate.ddl-auto: none
    show-sql: true


  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/reservou_db?serverTimezone=America/Sao_Paulo
    user: postgres
    password: aluno
    #    url: jdbc:postgresql://db:5432/reservou_db?serverTimezone=America/Sao_Paulo
    #    user: admin
    #    password: password

token:
  secret:
    signature: ${SECRET_SIGNATURE}
  expiration-time: 4
  refresh-expiration-time: 8