spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservou_db
    username: postgres
    password: aluno
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none

  flyway:
    enabled: true
    user: postgres
    password: aluno
    url: jdbc:postgresql://localhost:5432/reservou_db
    schemas:
      - reservou

token:
  secret:
    signature: ${SECRET_SIGNATURE}
  expiration-time: 4
  refresh-expiration-time: 8