spring:
  application:
    name: api-reservou
  profiles:
    active: hmg
  jpa:
    open-in-view: false
  jackson:
    time-zone: America/Sao_Paulo

server:
  servlet:
    context-path: /api-reservou-1.0

java:
  time:
    zoneid: America/Sao_Paulo